name: sem_team_4_conda_env
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.3.2
  - numpy=1.19.4
  - scipy=1.5.2
  - opencv=4.5.0
  - py-opencv=4.5.0
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  