name: autograder

on: [push]

jobs:
  autograder_test:
    runs-on: ubuntu-20.04
    
    steps:      
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Add conda to system path
      run: echo $CONDA/bin >> $GITHUB_PATH
      
    - name : Checkout Autograder
      uses: actions/checkout@v2
      with:
        repository: YoussefSGhatas/ip-project-grader
        
    - name : Remove sample submission
      run : rm -r ./students-work/*
      
    - name : Checkout Project
      uses: actions/checkout@v2
      with:
        path: students-work/9999/SEM-04

    - name : Copy test set into input folder
      run : |
        mkdir input
        image_files=(`find ./students-work/9999/SEM-04/PublicTestCases -type f -iname "*.png" -or -iname "*.jpg" -or -iname "*.jpeg" 2> /dev/null`) 
        cp "${image_files[@]}" ./input/

    - name: Run autograder
      run: |
        python ./run-students-docker-STD.py "$PWD/students-work/" "$PWD/input" "$PWD/output" -v 1

    - name : Test Results
      run : |
        mkdir output-correct
        tests=(`find ./students-work/9999/SEM-04/PublicTestCases -type f -iname "*.txt" 2> /dev/null`) 
        cp "${tests[@]}" ./output-correct/
        
        base_dir=`pwd`
        echo $base_dir
        cd ./output-correct/
        files=(*.txt)
        
        echo "_____________________________________________________________________"
        for filename in "${files[@]}"; do
            if [ ! -f "$base_dir/output/SEM04/$filename" ] ; then
                echo "$filename NOT FOUND IN OUR OUTPUT"
                sudo touch "$base_dir/output/SEM04/$filename"
            fi
            
            sudo python "$base_dir/students-work/9999/SEM-04/TestGrader.py" "$base_dir/output-correct/$filename" "$base_dir/output/SEM04/$filename"
            echo "_____________________________________________________________________"
        done

    - name: Upload test cases output
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test_cases_output
        path: ./output/SEM04/*
